#!/usr/bin/env python3
"""
GENIUS E. COLI ULTIMATE REPORTER 
================================================================================
Advanced HTML parser and gene-centric report generator for E. coli genomic data.
Processes outputs from EcoliTyper pipeline (MLST, serotype, CHTyper, phylogrouping,
AMRfinder, ABRicate databases) and creates an interactive HTML report with:
- Gene-centric tables (genes shown with all genomes that carry them)
- Sortable, searchable tables
- Combination tables (ST-O, ST-H, ST-O:H, ST-Phylogroup, ST-FimH, ST-FumC, ST-CH, full 5-way)
- FASTA QC metrics integration
- AI assistant guide
- Filter buttons for AMR and virulence genes
- CSV exports for all major tables

Author: Beckley Brown <brownbeckley94@gmail.com>
Affiliation: University of Ghana Medical School, Department of Medical Biochemistry
Version: 2.0.0
Date: 2026-04-17
License: MIT
================================================================================
"""

import os
import sys
import json
import re
import argparse
import pandas as pd
import numpy as np
from pathlib import Path
from typing import Dict, List, Set, Tuple, Any, Optional
from datetime import datetime
from collections import defaultdict, Counter
import warnings
warnings.filterwarnings('ignore')

from bs4 import BeautifulSoup

# =============================================================================
# HTML PARSER CLASS
# =============================================================================
class UltimateHTMLParser:
    """
    Parses all HTML reports generated by the EcoliTyper pipeline.
    Extracts typing data, AMR genes, virulence genes, and QC metrics.
    """
    
    def __init__(self):
        # Supported ABRicate database names (case-insensitive)
        self.abricate_databases = [
            'ncbi', 'card', 'resfinder', 'vfdb', 'argannot',
            'plasmidfinder', 'megares', 'ecoh', 'ecoli_vf', 'bacmet2'
        ]
    
    def normalize_sample_id(self, sample_id: str) -> str:
        """
        Normalize sample names by removing file extensions and path components.
        Ensures consistent matching across different report types.
        """
        sample = str(sample_id)
        # Remove common file extensions
        for ext in ['.fna', '.fasta', '.fa', '.gb', '.gbk', '.gbff', '.txt', '.tsv', '.csv']:
            if sample.endswith(ext):
                sample = sample[:-len(ext)]
        # Remove directory paths
        if '/' in sample or '\\' in sample:
            sample = Path(sample).name
        return sample.strip()
    
    def clean_st(self, st_str: str) -> str:
        """
        Clean MLST sequence type string by removing duplicate 'ST' prefixes.
        E.g., 'STST21' -> 'ST21', 'ST-131' -> 'ST131'
        """
        if not st_str or st_str == 'ND':
            return 'ND'
        st_str = str(st_str).strip()
        # Remove multiple 'ST' occurrences (case-insensitive)
        st_str = re.sub(r'^(ST)+', 'ST', st_str, flags=re.IGNORECASE)
        # Ensure it starts with 'ST'
        if not st_str.upper().startswith('ST'):
            st_str = 'ST' + st_str
        return st_str
    
    def parse_html_table(self, html_content: str, table_index: int = 0) -> pd.DataFrame:
        """
        Extract a table from HTML content using BeautifulSoup.
        Returns a pandas DataFrame or empty DataFrame if parsing fails.
        """
        try:
            soup = BeautifulSoup(html_content, 'html.parser')
            tables = soup.find_all('table')
            if not tables or table_index >= len(tables):
                return pd.DataFrame()
            table = tables[table_index]
            rows = table.find_all('tr')
            if not rows:
                return pd.DataFrame()
            headers = [th.get_text().strip() for th in rows[0].find_all(['th', 'td'])]
            data = []
            for row in rows[1:]:
                cols = row.find_all(['td', 'th'])
                if cols:
                    row_data = [col.get_text().strip() for col in cols]
                    if len(row_data) == len(headers):
                        data.append(row_data)
            if not data:
                return pd.DataFrame()
            return pd.DataFrame(data, columns=headers)
        except Exception as e:
            print(f"  ⚠️ Table parsing error: {e}")
            return pd.DataFrame()
    
    def parse_qc_report(self, file_path: Path) -> Dict[str, Dict]:
        """
        Parse FASTA QC summary HTML report.
        Returns dictionary: {sample_name: {metric_name: value, ...}}
        """
        print(f"  🧬 Parsing FASTA QC: {file_path.name}")
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                html = f.read()
            df = self.parse_html_table(html, 0)
            if df.empty:
                return {}
            # Identify sample column (usually 'Filename' or first column)
            sample_col = None
            for col in df.columns:
                if 'filename' in col.lower() or 'sample' in col.lower() or col == df.columns[0]:
                    sample_col = col
                    break
            if not sample_col:
                return {}
            results = {}
            for _, row in df.iterrows():
                sample_raw = row[sample_col]
                if not sample_raw:
                    continue
                sample = self.normalize_sample_id(sample_raw)
                qc_data = {}
                for col in df.columns:
                    if col == sample_col:
                        continue
                    val = row[col]
                    if pd.isna(val) or val == '' or val == 'ND':
                        qc_data[col] = 'ND'
                    else:
                        # Try to convert to numeric if possible
                        cleaned = str(val).replace('%', '').replace(',', '').strip()
                        try:
                            qc_data[col] = float(cleaned)
                        except:
                            qc_data[col] = str(val)
                results[sample] = qc_data
            print(f"    ✓ Parsed {len(results)} samples")
            return results
        except Exception as e:
            print(f"    ❌ Error parsing QC: {e}")
            return {}
    
    def parse_mlst_report(self, file_path: Path) -> Dict[str, Dict]:
        """
        Parse MLST summary HTML report.
        Returns dictionary: {sample_name: {'ST': str, 'Allele_Profile': str}}
        """
        print(f"  🧬 Parsing MLST: {file_path.name}")
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                html_content = f.read()
            soup = BeautifulSoup(html_content, 'html.parser')
            tables = soup.find_all('table')
            # Find table containing MLST data
            mlst_table = None
            for table in tables:
                if table.find(string=re.compile(r'Sample|ST|Allele', re.I)):
                    mlst_table = table
                    break
            if not mlst_table:
                mlst_table = soup.find('table')
            if not mlst_table:
                return {}
            rows = mlst_table.find_all('tr')
            if len(rows) < 2:
                return {}
            headers = [cell.get_text().strip() for cell in rows[0].find_all(['th', 'td'])]
            data = []
            for row in rows[1:]:
                cols = row.find_all(['td', 'th'])
                if cols:
                    row_data = [col.get_text().strip() for col in cols]
                    if len(row_data) >= 2:
                        data.append(row_data)
            if not data:
                return {}
            df = pd.DataFrame(data)
            # Align columns
            if len(df.columns) > len(headers):
                df = df.iloc[:, :len(headers)]
            df.columns = headers[:len(df.columns)]
            df.columns = [col.strip() for col in df.columns]
            # Identify sample column
            if 'Sample' in df.columns:
                df['normalized_sample'] = df['Sample'].apply(self.normalize_sample_id)
            elif any('sample' in col.lower() for col in df.columns):
                sample_col = [col for col in df.columns if 'sample' in col.lower()][0]
                df['normalized_sample'] = df[sample_col].apply(self.normalize_sample_id)
            else:
                df['normalized_sample'] = df.iloc[:, 0].apply(self.normalize_sample_id)
            results = {}
            for _, row in df.iterrows():
                sample = row['normalized_sample']
                # Extract ST
                st = 'ND'
                if 'ST' in df.columns:
                    st_raw = str(row['ST']) if pd.notna(row['ST']) else 'ND'
                    st = self.clean_st(st_raw)
                elif 'st' in [col.lower() for col in df.columns]:
                    st_col = [col for col in df.columns if col.lower() == 'st'][0]
                    st_raw = str(row[st_col]) if pd.notna(row[st_col]) else 'ND'
                    st = self.clean_st(st_raw)
                # Extract allele profile (optional)
                allele_profile = 'ND'
                if 'Allele Profile' in df.columns:
                    allele_profile = str(row['Allele Profile']) if pd.notna(row['Allele Profile']) else 'ND'
                results[sample] = {'ST': st, 'Allele_Profile': allele_profile}
            print(f"    ✓ Found {len(results)} samples")
            return results
        except Exception as e:
            print(f"    ❌ Error parsing MLST: {e}")
            return {}
    
    def parse_serotype_report(self, file_path: Path) -> Dict[str, Dict]:
        """
        Parse Serotype analysis HTML report.
        Returns dictionary: {sample_name: {'Serotype': str, 'O_Type': str, 'H_Type': str}}
        """
        print(f"  🧬 Parsing Serotype: {file_path.name}")
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                html_content = f.read()
            df = self.parse_html_table(html_content, 0)
            if df.empty:
                return {}
            df.columns = [col.strip() for col in df.columns]
            # Identify sample column
            sample_col = None
            for col in df.columns:
                if 'sample' in col.lower() or 'id' in col.lower():
                    sample_col = col
                    break
            if not sample_col:
                sample_col = df.columns[0]
            df['normalized_sample'] = df[sample_col].apply(self.normalize_sample_id)
            results = {}
            for _, row in df.iterrows():
                sample = row['normalized_sample']
                serotype = str(row.get('Serotype', 'ND')) if 'Serotype' in df.columns else 'ND'
                o_type = str(row.get('O-type', 'ND')) if 'O-type' in df.columns else str(row.get('O_Type', 'ND'))
                h_type = str(row.get('H-type', 'ND')) if 'H-type' in df.columns else str(row.get('H_Type', 'ND'))
                results[sample] = {'Serotype': serotype, 'O_Type': o_type, 'H_Type': h_type}
            print(f"    ✓ Found {len(results)} samples")
            return results
        except Exception as e:
            print(f"    ❌ Error parsing Serotype: {e}")
            return {}
    
    def parse_chtyper_report(self, file_path: Path) -> Dict[str, Dict]:
        """
        Parse CHTyper (FumC/FimH) HTML report.
        Returns dictionary: {sample_name: {'FumC_Type': str, 'FimH_Type': str, 'CH_Type': str}}
        """
        print(f"  🧬 Parsing CHTyper: {file_path.name}")
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                html_content = f.read()
            df = self.parse_html_table(html_content, 0)
            if df.empty:
                return {}
            df.columns = [col.strip() for col in df.columns]
            sample_col = None
            for col in df.columns:
                if 'sample' in col.lower() or 'id' in col.lower():
                    sample_col = col
                    break
            if not sample_col:
                sample_col = df.columns[0]
            df['normalized_sample'] = df[sample_col].apply(self.normalize_sample_id)
            results = {}
            for _, row in df.iterrows():
                sample = row['normalized_sample']
                fumc = str(row.get('FumC Type', 'ND')) if 'FumC Type' in df.columns else 'ND'
                fimh = str(row.get('FimH Type', 'ND')) if 'FimH Type' in df.columns else 'ND'
                ch_type = f"{fumc}:{fimh}" if fumc != 'ND' and fimh != 'ND' else 'ND'
                results[sample] = {'FumC_Type': fumc, 'FimH_Type': fimh, 'CH_Type': ch_type}
            print(f"    ✓ Found {len(results)} samples")
            return results
        except Exception as e:
            print(f"    ❌ Error parsing CHTyper: {e}")
            return {}
    
    def parse_phylogrouping_report(self, file_path: Path) -> Dict[str, Dict]:
        """
        Parse Phylogrouping (Clermont) HTML report.
        Returns dictionary: {sample_name: {'Clermont_Type': str}}
        """
        print(f"  🧬 Parsing Phylogrouping: {file_path.name}")
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                html_content = f.read()
            df = self.parse_html_table(html_content, 0)
            if df.empty:
                return {}
            df.columns = [col.strip() for col in df.columns]
            sample_col = None
            for col in df.columns:
                if 'sample' in col.lower() or 'id' in col.lower():
                    sample_col = col
                    break
            if not sample_col:
                sample_col = df.columns[0]
            df['normalized_sample'] = df[sample_col].apply(self.normalize_sample_id)
            results = {}
            for _, row in df.iterrows():
                sample = row['normalized_sample']
                clermont = 'ND'
                if 'Clermont Type' in df.columns:
                    clermont = str(row['Clermont Type']) if pd.notna(row['Clermont Type']) else 'ND'
                elif 'Type' in df.columns:
                    clermont = str(row['Type']) if pd.notna(row['Type']) else 'ND'
                results[sample] = {'Clermont_Type': clermont}
            print(f"    ✓ Found {len(results)} samples")
            return results
        except Exception as e:
            print(f"    ❌ Error parsing Phylogrouping: {e}")
            return {}
    
    def parse_amrfinder_report(self, file_path: Path) -> Tuple[Dict[str, List], Dict[str, Dict]]:
        """
        Parse AMRfinder HTML report.
        Returns:
            - genes_by_genome: {sample: [list of gene names]}
            - gene_frequencies: {gene: {'frequency': str, 'count': int, 'genomes': [samples], 'database': str}}
        """
        print(f"  🧬 Parsing AMRfinder: {file_path.name}")
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                html_content = f.read()
            soup = BeautifulSoup(html_content, 'html.parser')
            tables = soup.find_all('table')
            if len(tables) < 2:
                return {}, {}
            # Table 1: Gene Frequency (contains genome lists)
            gene_frequencies = {}
            df2 = self.parse_html_table(str(tables[1]), 0)
            if not df2.empty and 'Gene' in df2.columns:
                for _, row in df2.iterrows():
                    gene = str(row['Gene']).strip()
                    frequency = str(row.get('Frequency', '0')).strip()
                    genomes = []
                    if 'Genomes' in df2.columns and pd.notna(row.get('Genomes')):
                        genomes_str = str(row['Genomes'])
                        genomes = [self.normalize_sample_id(g.strip()) for g in genomes_str.split(',') if g.strip()]
                    count = 0
                    match = re.search(r'(\d+)', frequency)
                    if match:
                        count = int(match.group(1))
                    gene_frequencies[gene] = {
                        'frequency': frequency,
                        'count': count,
                        'genomes': genomes,
                        'database': 'amrfinder'
                    }
            # Table 0: Genes by Genome (reverse mapping)
            genes_by_genome = {}
            df1 = self.parse_html_table(str(tables[0]), 0)
            if not df1.empty and 'Genome' in df1.columns:
                for _, row in df1.iterrows():
                    sample = self.normalize_sample_id(row['Genome'])
                    genes = []
                    if pd.notna(row.get('Genes Detected')):
                        gene_str = str(row['Genes Detected'])
                        genes = [g.strip() for g in gene_str.split(',') if g.strip()]
                    genes_by_genome[sample] = genes
            print(f"    ✓ Found {len(genes_by_genome)} samples, {len(gene_frequencies)} genes")
            return genes_by_genome, gene_frequencies
        except Exception as e:
            print(f"    ❌ Error parsing AMRfinder: {e}")
            return {}, {}
    
    def parse_abricate_database_report(self, file_path: Path) -> Tuple[Dict[str, List], Dict[str, Dict]]:
        """
        Parse any ABRicate database HTML report.
        Returns:
            - genes_by_genome: {sample: [list of gene names]}
            - gene_frequencies: {gene: {'frequency': str, 'count': int, 'genomes': [samples], 'database': str}}
        """
        print(f"  🧬 Parsing ABRicate: {file_path.name}")
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                html_content = f.read()
            soup = BeautifulSoup(html_content, 'html.parser')
            tables = soup.find_all('table')
            if len(tables) < 2:
                return {}, {}
            # Identify database name from filename or title
            db_name = 'unknown'
            title_tag = soup.find('title')
            if title_tag:
                title_text = title_tag.get_text()
                match = re.search(r'(\w+)\s+Database', title_text, re.I)
                if match:
                    db_name = match.group(1).lower()
                else:
                    db_name = file_path.stem.lower().replace('ecoli_', '').replace('_summary_report', '')
            # Table 1: Gene Frequency (contains genome lists)
            gene_frequencies = {}
            df2 = self.parse_html_table(str(tables[1]), 0)
            if not df2.empty and 'Gene' in df2.columns:
                for _, row in df2.iterrows():
                    gene = str(row['Gene']).strip()
                    frequency = str(row.get('Frequency', '0')).strip()
                    genomes = []
                    if 'Genomes' in df2.columns and pd.notna(row.get('Genomes')):
                        genomes_str = str(row['Genomes'])
                        genomes = [self.normalize_sample_id(g.strip()) for g in genomes_str.split(',') if g.strip()]
                    count = 0
                    match = re.search(r'(\d+)', frequency)
                    if match:
                        count = int(match.group(1))
                    gene_frequencies[gene] = {
                        'frequency': frequency,
                        'count': count,
                        'genomes': genomes,
                        'database': db_name
                    }
            # Table 0: Genes by Genome (reverse mapping)
            genes_by_genome = {}
            df1 = self.parse_html_table(str(tables[0]), 0)
            if not df1.empty:
                # Find sample column
                sample_col = None
                for col in df1.columns:
                    if 'genome' in col.lower() or 'sample' in col.lower():
                        sample_col = col
                        break
                if sample_col:
                    for _, row in df1.iterrows():
                        sample = self.normalize_sample_id(row[sample_col])
                        genes = []
                        # Find genes column (usually 'Genes' or 'Detected')
                        genes_col = None
                        for col in df1.columns:
                            if 'genes' in col.lower() or 'detected' in col.lower():
                                genes_col = col
                                break
                        if genes_col and pd.notna(row.get(genes_col)):
                            gene_str = str(row[genes_col])
                            genes = [g.strip() for g in gene_str.split(',') if g.strip()]
                        genes_by_genome[sample] = genes
            print(f"    ✓ {db_name.upper()}: {len(genes_by_genome)} samples, {len(gene_frequencies)} genes")
            return genes_by_genome, gene_frequencies
        except Exception as e:
            print(f"    ❌ Error parsing ABRicate report: {e}")
            return {}, {}


# =============================================================================
# DATA ANALYZER CLASS
# =============================================================================
class UltimateDataAnalyzer:
    """
    Processes integrated data to create gene-centric tables and cross-genome patterns.
    """
    
    def __init__(self):
        # Critical AMR genes for E. coli (ESBL, carbapenemases, mcr, qnr, etc.)
        self.critical_amr_genes = {
            'blaCTX-M', 'blaSHV', 'blaTEM', 'blaKPC', 'blaNDM', 'blaOXA', 'blaVIM', 'blaIMP',
            'mcr-1', 'mcr-2', 'mcr-3', 'mcr-4', 'mcr-5', 'mcr-6', 'mcr-7', 'mcr-8', 'mcr-9', 'mcr-10',
            'qnrA', 'qnrB', 'qnrC', 'qnrD', 'qnrS', 'aac(6\')-Ib-cr'
        }
        # Critical virulence genes for E. coli (Shiga toxins, intimin, CNF1, hemolysin, etc.)
        self.critical_virulence_genes = {
            'stx1', 'stx2', 'stx1A', 'stx1B', 'stx2A', 'stx2B',
            'cnf1', 'hlyA', 'hlyB', 'hlyC', 'hlyD', 'eae', 'lt', 'st'
        }
    
    def create_gene_centric_tables(self, integrated_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Convert sample-centric gene lists into gene-centric tables.
        Each gene is shown once with all genomes that contain it.
        """
        gene_centric = {
            'amr_databases': {},
            'virulence_databases': {},
            'combined_gene_frequencies': []
        }
        
        # Process AMRfinder data
        if 'amrfinder' in integrated_data.get('gene_frequencies', {}):
            amr_data = integrated_data['gene_frequencies']['amrfinder']
            gene_list = []
            for gene, data in amr_data.items():
                gene_list.append({
                    'gene': gene,
                    'database': 'AMRfinder',
                    'frequency': data.get('frequency', '0'),
                    'count': data.get('count', 0),
                    'genomes': data.get('genomes', [])
                })
            gene_centric['amr_databases']['amrfinder'] = sorted(gene_list, key=lambda x: x['count'], reverse=True)
        
        # Process ABRicate databases
        if 'abricate' in integrated_data.get('gene_frequencies', {}):
            for db_name, db_genes in integrated_data['gene_frequencies']['abricate'].items():
                gene_list = []
                for gene, data in db_genes.items():
                    gene_list.append({
                        'gene': gene,
                        'database': db_name.upper(),
                        'frequency': data.get('frequency', '0'),
                        'count': data.get('count', 0),
                        'genomes': data.get('genomes', [])
                    })
                if gene_list:
                    gene_list.sort(key=lambda x: x['count'], reverse=True)
                    # Classify as virulence or AMR based on database name
                    if db_name in ['vfdb', 'ecoli_vf']:
                        gene_centric['virulence_databases'][db_name] = gene_list
                    else:
                        gene_centric['amr_databases'][db_name] = gene_list
        
        # Combined list for pattern discovery
        all_genes = []
        for db_type in ['amr_databases', 'virulence_databases']:
            for genes in gene_centric.get(db_type, {}).values():
                all_genes.extend(genes)
        all_genes.sort(key=lambda x: x['count'], reverse=True)
        gene_centric['combined_gene_frequencies'] = all_genes
        return gene_centric
    
    def create_cross_genome_patterns(self, integrated_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate cross-genome patterns including:
        - Distributions of STs, serotypes, phylogroups, CH types, O/H/FumC/FimH types
        - Combination tables (ST-O, ST-H, ST-O:H, ST-Phylogroup, ST-FimH, ST-FumC, ST-CH, full 5-way)
        - Gene co-occurrence matrix
        - High-risk combinations (critical AMR + critical virulence)
        """
        patterns = {
            # Basic counters
            'st_distribution': Counter(),
            'serotype_distribution': Counter(),
            'phylogroup_distribution': Counter(),
            'ch_type_distribution': Counter(),
            'o_type_distribution': Counter(),
            'h_type_distribution': Counter(),
            'fumc_type_distribution': Counter(),
            'fimh_type_distribution': Counter(),
            # Combination tables (sample lists)
            'st_o_combinations': defaultdict(list),
            'st_h_combinations': defaultdict(list),
            'st_oh_combinations': defaultdict(list),
            'st_phylogroup_combinations': defaultdict(list),
            'st_fimh_combinations': defaultdict(list),
            'st_fumc_combinations': defaultdict(list),
            'st_fumc_fimh_combinations': defaultdict(list),
            'st_oh_phylo_fumc_fimh_combinations': defaultdict(list),
            # Gene co-occurrence
            'gene_cooccurrence': defaultdict(Counter),
            'high_risk_combinations': []
        }
        
        samples_data = integrated_data.get('samples', {})
        gene_centric = integrated_data.get('gene_centric', {})
        
        # Build sample->genes mapping for co-occurrence
        sample_genes = defaultdict(list)
        for db_type in ['amr_databases', 'virulence_databases']:
            for genes in gene_centric.get(db_type, {}).values():
                for gene_data in genes:
                    for genome in gene_data['genomes']:
                        if gene_data['gene'] not in sample_genes[genome]:
                            sample_genes[genome].append(gene_data['gene'])
        
        # Process each sample
        for sample, data in samples_data.items():
            st = data.get('mlst', {}).get('ST', 'ND')
            serotype = data.get('serotype', {}).get('Serotype', 'ND')
            o_type = data.get('serotype', {}).get('O_Type', 'ND')
            h_type = data.get('serotype', {}).get('H_Type', 'ND')
            phylogroup = data.get('phylogrouping', {}).get('Clermont_Type', 'ND')
            fumc = data.get('chtyper', {}).get('FumC_Type', 'ND')
            fimh = data.get('chtyper', {}).get('FimH_Type', 'ND')
            ch_type = data.get('chtyper', {}).get('CH_Type', 'ND')
            
            # Update counters (only if not 'ND')
            if st != 'ND':
                patterns['st_distribution'][st] += 1
            if serotype != 'ND':
                patterns['serotype_distribution'][serotype] += 1
            if o_type != 'ND':
                patterns['o_type_distribution'][o_type] += 1
            if h_type != 'ND':
                patterns['h_type_distribution'][h_type] += 1
            if phylogroup != 'ND':
                patterns['phylogroup_distribution'][phylogroup] += 1
            if ch_type != 'ND':
                patterns['ch_type_distribution'][ch_type] += 1
            if fumc != 'ND':
                patterns['fumc_type_distribution'][fumc] += 1
            if fimh != 'ND':
                patterns['fimh_type_distribution'][fimh] += 1
            
            # Build combination tables (only when both parts are known)
            if st != 'ND' and o_type != 'ND':
                patterns['st_o_combinations'][f"{st} - {o_type}"].append(sample)
            if st != 'ND' and h_type != 'ND':
                patterns['st_h_combinations'][f"{st} - {h_type}"].append(sample)
            if st != 'ND' and serotype != 'ND':
                patterns['st_oh_combinations'][f"{st} - {serotype}"].append(sample)
            if st != 'ND' and phylogroup != 'ND':
                patterns['st_phylogroup_combinations'][f"{st} - {phylogroup}"].append(sample)
            if st != 'ND' and fimh != 'ND':
                patterns['st_fimh_combinations'][f"{st} - {fimh}"].append(sample)
            if st != 'ND' and fumc != 'ND':
                patterns['st_fumc_combinations'][f"{st} - {fumc}"].append(sample)
            if st != 'ND' and ch_type != 'ND':
                patterns['st_fumc_fimh_combinations'][f"{st} - {ch_type}"].append(sample)
            if st != 'ND' and serotype != 'ND' and phylogroup != 'ND' and ch_type != 'ND':
                full_combo = f"{st} - {serotype} - {phylogroup} - {ch_type}"
                patterns['st_oh_phylo_fumc_fimh_combinations'][full_combo].append(sample)
            
            # Gene co-occurrence
            genes = sample_genes.get(sample, [])
            for i, g1 in enumerate(genes):
                for g2 in genes[i+1:]:
                    patterns['gene_cooccurrence'][g1][g2] += 1
            
            # High-risk combinations: sample carries both critical AMR and critical virulence genes
            amr_genes = data.get('amr_genes', [])
            virulence_genes = data.get('virulence_genes', [])
            critical_amr = [g for g in amr_genes if any(crit.lower() in g.lower() for crit in self.critical_amr_genes)]
            critical_vir = [g for g in virulence_genes if any(crit.lower() in g.lower() for crit in self.critical_virulence_genes)]
            if critical_amr and critical_vir:
                patterns['high_risk_combinations'].append({
                    'sample': sample,
                    'st': st,
                    'serotype': serotype,
                    'critical_amr_genes': critical_amr,
                    'critical_virulence_genes': critical_vir
                })
        
        return patterns


# =============================================================================
# HTML GENERATOR CLASS
# =============================================================================
class UltimateHTMLGenerator:
    """
    Generates a standalone interactive HTML report with all sections,
    sortable tables, search boxes, filter buttons, and export options.
    """
    
    def __init__(self, data_analyzer: UltimateDataAnalyzer):
        self.data_analyzer = data_analyzer
    
    def generate_main_report(self, integrated_data: Dict[str, Any], output_dir: Path) -> str:
        """Generate the ultimate HTML report and save to file."""
        print("\n🎨 Generating ULTIMATE HTML report...")
        html = self._create_ultimate_html(
            metadata=integrated_data.get('metadata', {}),
            samples_data=integrated_data.get('samples', {}),
            patterns=integrated_data.get('patterns', {}),
            gene_centric=integrated_data.get('gene_centric', {}),
            qc_data=integrated_data.get('qc_data', {}),
            integrated_data=integrated_data
        )
        output_file = output_dir / "genius_ultimate_report.html"
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(html)
        print(f"    ✅ HTML report saved: {output_file}")
        return str(output_file)
    
    def _create_ultimate_html(self, **kwargs) -> str:
        """
        Assemble the full HTML document with CSS, JavaScript, and all tab contents.
        """
        # CSS styles (embedded for portability)
        css = """
        <style>
        :root {
            --summary-color: #4CAF50; --samples-color: #2196F3; --mlst-color: #FF9800;
            --serotype-color: #9C27B0; --chtype-color: #009688; --phylogroup-color: #795548;
            --amr-color: #F44336; --virulence-color: #E91E63; --patterns-color: #FF5722;
            --qc-color: #607D8B; --aiguide-color: #3F51B5; --export-color: #3F51B5;
        }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; background: #f5f5f5; min-width: 1200px; }
        .container { max-width: none; margin: 0 auto; padding: 20px; width: 100%; overflow-x: auto; }
        .main-header { background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%); color: white; padding: 30px; border-radius: 15px; margin-bottom: 30px; text-align: center; }
        .main-header h1 { font-size: 2.8em; margin-bottom: 10px; color: white; }
        .metadata-bar { background: rgba(255,255,255,0.1); padding: 15px; border-radius: 10px; margin: 20px 0; display: flex; justify-content: space-around; flex-wrap: wrap; gap: 15px; }
        .dashboard-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin-bottom: 30px; }
        .dashboard-card { background: white; padding: 25px; border-radius: 12px; box-shadow: 0 5px 20px rgba(0,0,0,0.1); text-align: center; transition: all 0.3s ease; cursor: pointer; border-left: 5px solid; }
        .dashboard-card:hover { transform: translateY(-10px); }
        .card-number { font-size: 3em; font-weight: bold; margin: 15px 0; background: linear-gradient(90deg, #1e3c72, #2a5298); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
        .tab-navigation { display: flex; gap: 5px; margin-bottom: 20px; flex-wrap: wrap; background: white; padding: 15px; border-radius: 12px; position: sticky; top: 10px; z-index: 100; }
        .tab-button { padding: 12px 25px; background: #f5f5f5; border: none; border-radius: 8px; cursor: pointer; font-weight: 600; color: #666; transition: all 0.3s ease; display: flex; align-items: center; gap: 8px; }
        .tab-button.active { color: white; }
        .tab-button.summary.active { background: var(--summary-color); }
        .tab-button.samples.active { background: var(--samples-color); }
        .tab-button.mlst.active { background: var(--mlst-color); }
        .tab-button.serotype.active { background: var(--serotype-color); }
        .tab-button.chtype.active { background: var(--chtype-color); }
        .tab-button.phylogroup.active { background: var(--phylogroup-color); }
        .tab-button.amr.active { background: var(--amr-color); }
        .tab-button.virulence.active { background: var(--virulence-color); }
        .tab-button.patterns.active { background: var(--patterns-color); }
        .tab-button.qc.active { background: var(--qc-color); }
        .tab-button.aiguide.active { background: var(--aiguide-color); }
        .tab-button.export.active { background: var(--export-color); }
        .tab-content { display: none; background: white; padding: 30px; border-radius: 15px; margin-bottom: 30px; width: 100%; overflow-x: auto; animation: fadeIn 0.5s ease; }
        .tab-content.active { display: block; }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
        .section-header { color: #2c3e50; margin-bottom: 25px; padding-bottom: 15px; border-bottom: 3px solid; font-size: 1.8em; display: flex; justify-content: space-between; }
        .data-table { width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 0.95em; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .data-table th { background: #2c3e50; color: white; padding: 15px; text-align: left; cursor: pointer; white-space: nowrap; }
        .data-table th:hover { background: #1a252f; }
        .data-table td { padding: 12px; border-bottom: 1px solid #e0e0e0; vertical-align: top; word-wrap: break-word; }
        .data-table tr:hover { background: #f8f9fa; }
        .sort-icon { margin-left: 5px; font-size: 0.8em; opacity: 0.6; }
        .search-box { width: 100%; padding: 12px; margin-bottom: 20px; border: 2px solid #e0e0e0; border-radius: 8px; font-size: 1em; }
        .action-buttons { display: flex; gap: 10px; margin: 20px 0; flex-wrap: wrap; clear: both;  }
        .action-btn { padding: 10px 20px; border: none; border-radius: 8px; cursor: pointer; font-weight: 600; display: inline-flex; align-items: center; gap: 8px; transition: 0.3s; }
        .action-btn:hover { transform: translateY(-2px); }
        .btn-primary { background: #1e3c72; color: white; }
        .btn-danger { background: #dc3545; color: white; }
        .btn-warning { background: #ffc107; color: black; }
        .btn-info { background: #17a2b8; color: white; }
        .btn-secondary { background: #6c757d; color: white; }
        .btn-light { background: #f8f9fa; color: #212529; border: 1px solid #dee2e6; }
        .badge { display: inline-block; padding: 5px 15px; border-radius: 20px; font-size: 0.85em; font-weight: 600; margin: 2px; }
        .badge-mrsa { background: #8B0000; color: white; }
        .alert-box { padding: 20px; border-radius: 10px; margin: 20px 0; display: flex; align-items: center; gap: 20px; border-left: 5px solid; }
        .alert-info { background: #d1ecf1; color: #0c5460; border-left-color: #17a2b8; }
        .alert-danger { background: #f8d7da; color: #721c24; border-left-color: #dc3545; }
        .genome-list { display: flex; flex-wrap: wrap; gap: 5px; }
        .genome-tag { background: #e3f2fd; color: #1976d2; padding: 3px 10px; border-radius: 12px; font-size: 0.85em; border: 1px solid #bbdefb; white-space: nowrap; }
        .footer { text-align: center; padding: 30px; background: linear-gradient(135deg, #2c3e50, #34495e); color: white; border-radius: 15px; margin-top: 40px; }
        @media print { .tab-navigation, .dashboard-grid, .search-box, .action-buttons, .print-section-btn { display: none; } .tab-content.active { display: block; } }
        </style>
        """
        
        # JavaScript for interactive features
        js = """
        <script>
        function switchTab(tabName) {
            document.querySelectorAll('.tab-content').forEach(t => t.classList.remove('active'));
            document.querySelectorAll('.tab-button').forEach(b => b.classList.remove('active'));
            document.getElementById(tabName + '-tab').classList.add('active');
            event.currentTarget.classList.add('active');
            window.location.hash = tabName;
        }
        function searchTable(tableId, searchId) {
            const filter = document.getElementById(searchId).value.toUpperCase();
            const rows = document.getElementById(tableId).getElementsByTagName('tr');
            for (let i = 1; i < rows.length; i++) {
                let found = false;
                for (let cell of rows[i].getElementsByTagName('td')) {
                    if (cell.textContent.toUpperCase().indexOf(filter) > -1) { found = true; break; }
                }
                rows[i].style.display = found ? '' : 'none';
            }
        }
        function sortTable(tableId, colIndex, type) {
            const table = document.getElementById(tableId);
            const tbody = table.tBodies[0];
            const rows = Array.from(tbody.rows);
            const isAscending = table.getAttribute('data-sort-dir') !== 'asc';
            rows.sort((a,b) => {
                let aVal = a.cells[colIndex].innerText.trim();
                let bVal = b.cells[colIndex].innerText.trim();
                if (type === 'number') {
                    aVal = parseFloat(aVal.replace(/,/g,'')) || 0;
                    bVal = parseFloat(bVal.replace(/,/g,'')) || 0;
                    return isAscending ? aVal - bVal : bVal - aVal;
                } else {
                    return isAscending ? aVal.localeCompare(bVal) : bVal.localeCompare(aVal);
                }
            });
            tbody.append(...rows);
            table.setAttribute('data-sort-dir', isAscending ? 'asc' : 'desc');
            const headers = table.querySelectorAll('th');
            headers.forEach((th,idx) => { let icon = th.querySelector('.sort-icon'); if(icon) icon.innerHTML = '⇅'; });
            const currentHeader = headers[colIndex];
            const icon = currentHeader.querySelector('.sort-icon');
            if(icon) icon.innerHTML = isAscending ? '↑' : '↓';
        }
        function exportTableToCSV(tableId, filename) {
            const rows = document.getElementById(tableId).querySelectorAll('tr');
            const csv = [];
            for (let row of rows) {
                const cols = row.querySelectorAll('td, th');
                const rowData = Array.from(cols).map(c => '"' + c.innerText.replace(/"/g, '""') + '"');
                csv.push(rowData.join(','));
            }
            const blob = new Blob([csv.join('\\n')], {type: 'text/csv'});
            const a = document.createElement('a');
            a.href = URL.createObjectURL(blob);
            a.download = filename;
            a.click();
            URL.revokeObjectURL(a.href);
        }
        function printSection(sectionId) {
            const content = document.getElementById(sectionId);
            const win = window.open('', '_blank');
            win.document.write('<html><head><title>Print</title><style>' + document.querySelector('style').textContent + '</style></head><body>');
            win.document.write(content.innerHTML);
            win.document.write('</body></html>');
            win.document.close();
            win.print();
        }
        document.addEventListener('DOMContentLoaded', function() {
            const hash = window.location.hash.substring(1);
            if(hash) {
                let btn = document.querySelector(`.tab-button.${hash}`);
                if(btn) btn.click();
            } else document.querySelector('.tab-button').click();
            document.querySelectorAll('.data-table').forEach(table => {
                const headers = table.querySelectorAll('th');
                headers.forEach((th, idx) => {
                    const type = th.getAttribute('data-sort') || 'string';
                    th.style.cursor = 'pointer';
                    th.addEventListener('click', () => sortTable(table.id, idx, type));
                    let icon = document.createElement('span');
                    icon.className = 'sort-icon';
                    icon.innerHTML = '⇅';
                    th.appendChild(icon);
                });
            });
        });
        </script>
        """
        
        # Extract data for dashboard and tabs
        metadata = kwargs['metadata']
        samples = kwargs['samples_data']
        patterns = kwargs['patterns']
        gene_centric = kwargs['gene_centric']
        qc_data = kwargs.get('qc_data', {})
        total_amr = sum(len(genes) for genes in gene_centric.get('amr_databases', {}).values())
        total_vir = sum(len(genes) for genes in gene_centric.get('virulence_databases', {}).values())
        high_risk_count = len(patterns.get('high_risk_combinations', []))
        
        # Assemble HTML document
        html = f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>GENIUS E.coli Ultimate Report</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
{css}{js}</head>
<body><div class="container">
<div class="main-header"><h1><i class="fas fa-dna"></i> GENIUS E.coli Ultimate Analysis Report</h1>
<p>Gene-Centric Cross-Genome Analysis with Complete Genome Lists</p>
<div class="metadata-bar"><div class="metadata-item"><i class="fas fa-calendar"></i> {metadata.get('analysis_date','Unknown')}</div>
<div class="metadata-item"><i class="fas fa-database"></i> Samples: {len(samples)}</div>
<div class="metadata-item"><i class="fas fa-user-md"></i> GENIUS Ultimate v2.0.0</div>
<div class="metadata-item"><i class="fas fa-university"></i> University of Ghana Medical School</div></div></div>
<div class="dashboard-grid">
    <div class="dashboard-card card-summary" onclick="switchTab('summary')"><div class="card-number">{len(samples)}</div><div class="card-label">Total Samples</div><i class="fas fa-vial fa-2x"></i></div>
    <div class="dashboard-card card-mlst" onclick="switchTab('mlst')"><div class="card-number">{len(patterns.get('st_distribution',{}))}</div><div class="card-label">Unique STs</div><i class="fas fa-code-branch fa-2x"></i></div>
    <div class="dashboard-card card-serotype" onclick="switchTab('serotype')"><div class="card-number">{len(patterns.get('serotype_distribution',{}))}</div><div class="card-label">Serotypes</div><i class="fas fa-tag fa-2x"></i></div>
    <div class="dashboard-card card-amr" onclick="switchTab('amr')"><div class="card-number">{total_amr}</div><div class="card-label">AMR Genes</div><i class="fas fa-biohazard fa-2x"></i></div>
    <div class="dashboard-card card-virulence" onclick="switchTab('virulence')"><div class="card-number">{total_vir}</div><div class="card-label">Virulence Genes</div><i class="fas fa-virus fa-2x"></i></div>
    <div class="dashboard-card card-patterns" onclick="switchTab('patterns')"><div class="card-number">{high_risk_count}</div><div class="card-label">High-Risk Combos</div><i class="fas fa-project-diagram fa-2x"></i></div>
</div>
<div class="tab-navigation">
    <button class="tab-button summary active" onclick="switchTab('summary')"><i class="fas fa-chart-pie"></i> Summary</button>
    <button class="tab-button samples" onclick="switchTab('samples')"><i class="fas fa-list-alt"></i> Sample Overview</button>
    <button class="tab-button mlst" onclick="switchTab('mlst')"><i class="fas fa-code-branch"></i> MLST Analysis</button>
    <button class="tab-button serotype" onclick="switchTab('serotype')"><i class="fas fa-tag"></i> Serotype</button>
    <button class="tab-button chtype" onclick="switchTab('chtype')"><i class="fas fa-project-diagram"></i> CH Type</button>
    <button class="tab-button phylogroup" onclick="switchTab('phylogroup')"><i class="fas fa-sitemap"></i> Phylogroup</button>
    <button class="tab-button amr" onclick="switchTab('amr')"><i class="fas fa-biohazard"></i> AMR Genes</button>
    <button class="tab-button virulence" onclick="switchTab('virulence')"><i class="fas fa-virus"></i> Virulence</button>
    <button class="tab-button patterns" onclick="switchTab('patterns')"><i class="fas fa-project-diagram"></i> Patterns</button>
    <button class="tab-button qc" onclick="switchTab('qc')"><i class="fas fa-chart-line"></i> FASTA QC</button>
    <button class="tab-button aiguide" onclick="switchTab('aiguide')"><i class="fas fa-robot"></i> AI Guide</button>
    <button class="tab-button export" onclick="switchTab('export')"><i class="fas fa-download"></i> Export</button>
</div>
<div id="summary-tab" class="tab-content active">{self._summary_section(kwargs)}</div>
<div id="samples-tab" class="tab-content">{self._samples_section(kwargs)}</div>
<div id="mlst-tab" class="tab-content">{self._mlst_section(kwargs)}</div>
<div id="serotype-tab" class="tab-content">{self._serotype_section(kwargs)}</div>
<div id="chtype-tab" class="tab-content">{self._chtype_section(kwargs)}</div>
<div id="phylogroup-tab" class="tab-content">{self._phylogroup_section(kwargs)}</div>
<div id="amr-tab" class="tab-content">{self._amr_section(kwargs)}</div>
<div id="virulence-tab" class="tab-content">{self._virulence_section(kwargs)}</div>
<div id="patterns-tab" class="tab-content">{self._patterns_section(kwargs)}</div>
<div id="qc-tab" class="tab-content">{self._qc_section(kwargs)}</div>
<div id="aiguide-tab" class="tab-content">{self._aiguide_section(kwargs)}</div>
<div id="export-tab" class="tab-content">{self._export_section(kwargs)}</div>
<div class="footer"><h3>GENIUS E.coli Ultimate Reporter v2.0.0</h3><p>University of Ghana Medical School | Brown Beckley &lt;brownbeckley94@gmail.com&gt;</p><p>Generated on {metadata.get('analysis_date','Unknown')}</p></div>
</div></body></html>"""
        return html
    
    # -------------------------------------------------------------------------
    # Section generators (each returns HTML for a specific tab)
    # -------------------------------------------------------------------------
    
    def _summary_section(self, kwargs):
        samples = kwargs['samples_data']
        patterns = kwargs['patterns']
        total = len(samples)
        st_unique = len(patterns.get('st_distribution', {}))
        sero_unique = len(patterns.get('serotype_distribution', {}))
        phylo_unique = len(patterns.get('phylogroup_distribution', {}))
        ch_unique = len(patterns.get('ch_type_distribution', {}))
        amr_total = sum(len(genes) for genes in kwargs['gene_centric'].get('amr_databases', {}).values())
        vir_total = sum(len(genes) for genes in kwargs['gene_centric'].get('virulence_databases', {}).values())
        high_risk = len(patterns.get('high_risk_combinations', []))
        return f"""
        <div class="alert-box alert-info"><i class="fas fa-info-circle fa-2x"></i><div><h3>Analysis Overview</h3><p>Gene-centric report for <strong>{total}</strong> E. coli genomes. Each gene shown with all genomes containing it.</p></div></div>
        <div class="action-buttons"><button class="action-btn btn-primary" onclick="switchTab('amr')"><i class="fas fa-biohazard"></i> View AMR Genes</button>
        <button class="action-btn btn-success" onclick="switchTab('virulence')"><i class="fas fa-virus"></i> View Virulence</button>
        <button class="action-btn btn-danger" onclick="switchTab('patterns')"><i class="fas fa-exclamation-triangle"></i> High-Risk Combos</button></div>
        <h3>Key Statistics</h3><div class="scrollable-table"><table id="summary-stats" class="data-table"><thead><tr><th data-sort="string">Metric</th><th data-sort="string">Count</th><th>Details</th></tr></thead><tbody>
        <tr><td>Total Samples</th><td><strong>{total}</strong></th><td>Complete genomic analysis</th></tr>
        <tr><td>Unique STs</th><td><strong>{st_unique}</strong></th><td>MLST typing</th></tr>
        <tr><td>Unique Serotypes</th><td><strong>{sero_unique}</strong></th><td>O:H antigens</th></tr>
        <tr><td>Unique Phylogroups</th><td><strong>{phylo_unique}</strong></th><td>Clermont scheme</th></tr>
        <tr><td>Unique CH Types</th><td><strong>{ch_unique}</strong></th><td>FumC:FimH</th></tr>
        <tr><td>AMR Genes</th><td><strong>{amr_total}</strong></th><td>All databases</th></tr>
        <tr><td>Virulence Genes</th><td><strong>{vir_total}</strong></th><td>VFDB/Ecoli_VF</th></tr>
        <tr><td>High-Risk Combos</th><td><strong class="badge badge-mrsa">{high_risk}</strong></th><td>Critical AMR + Virulence</th></tr>
        </tbody></table></div>
        """
    
    def _samples_section(self, kwargs):
        samples = kwargs['samples_data']
        html = """
        <div class="alert-box alert-info">
            <i class="fas fa-info-circle fa-2x"></i>
            <div>
                <h3>Population Structure Overview</h3>
                <p>This table summarises the key typing results for each genome. Understanding the population structure helps identify dominant clones, track outbreaks, and link genotypes to phenotypes.</p>
                <ul>
                    <li><strong>MLST (Sequence Type)</strong>: Gold standard for global epidemiology. Clonal complexes indicate recent common ancestry.</li>
                    <li><strong>Serotype (O:H)</strong>: Surface antigens used for traditional typing. Specific O:H combinations are associated with pathotypes (e.g., O157:H7 with STEC).</li>
                    <li><strong>Phylogroup (Clermont)</strong>: Deep evolutionary lineages (A, B1, B2, C, D, E, F, G). Phylogroup B2 and D are often extra-intestinal pathogenic (ExPEC), while A and B1 are commensal/environmental.</li>
                    <li><strong>CH Type (FumC:FimH)</strong>: Fine‑scale typing based on housekeeping (FumC) and adhesin (FimH) genes. FimH alleles correlate with tropism and virulence.</li>
                </ul>
            </div>
        </div>
        <input type="text" class="search-box" id="search-samples" onkeyup="searchTable('samples-table','search-samples')" placeholder="🔍 Search...">
        <div class="action-buttons"><button class="action-btn btn-primary" onclick="exportTableToCSV('samples-table','sample_overview.csv')"><i class="fas fa-download"></i> Export CSV</button></div>
        <div class="scrollable-table"><table id="samples-table" class="data-table"><thead><tr><th data-sort="string">Sample</th><th data-sort="string">ST</th><th data-sort="string">Serotype</th><th data-sort="string">Phylogroup</th><th data-sort="string">CH Type</th><th data-sort="number">Virulence Count</th></tr></thead><tbody>
        """
        for sample, data in samples.items():
            st = data.get('mlst',{}).get('ST','ND')
            sero = data.get('serotype',{}).get('Serotype','ND')
            phylo = data.get('phylogrouping',{}).get('Clermont_Type','ND')
            cht = data.get('chtyper',{}).get('CH_Type','ND')
            vir_cnt = len(data.get('virulence_genes',[]))
            html += f'<tr><td><strong>{sample}</strong></td><td>{st}</td><td>{sero}</td><td>{phylo}</td><td>{cht}</td><td>{vir_cnt}</td></tr>'
        html += '</tbody></table></div>'
        return html
    
    def _mlst_section(self, kwargs):
        patterns = kwargs['patterns']
        st_dist = patterns.get('st_distribution', Counter())
        total = sum(st_dist.values())
        html = f"""
        <div class="alert-box alert-info"><i class="fas fa-info-circle"></i><div><h3>MLST Analysis</h3><p>Multi‑Locus Sequence Typing (MLST) uses internal fragments of seven housekeeping genes. It is highly reproducible and defines Sequence Types (STs). Closely related STs belong to the same Clonal Complex (CC).</p><p><strong>{len(st_dist)} unique STs</strong> identified.</p></div></div>
        <div class="scrollable-table"><table id="mlst-table" class="data-table"><thead><tr><th data-sort="string">ST</th><th data-sort="number">Count</th><th data-sort="number">Percentage</th><th data-sort="string">Associated Serotypes</th></tr></thead><tbody>
        """
        for st, cnt in st_dist.most_common():
            pct = cnt/total*100
            seros = set()
            for combo in patterns.get('st_oh_combinations',{}):
                if f"{st} - " in combo:
                    seros.add(combo.split(" - ")[1])
            sero_str = ', '.join(seros) if seros else 'ND'
            html += f'<tr><td><strong>{st}</strong></td><td>{cnt}</td><td>{pct:.1f}%</td><td>{sero_str}</td></tr>'
        html += '</tbody></table></div>'
        # All combination tables
        combos = [
            ('st_o_combinations', 'ST-O', 'ST - O antigen'),
            ('st_h_combinations', 'ST-H', 'ST - H antigen'),
            ('st_oh_combinations', 'ST-O:H', 'ST - Serotype (O:H)'),
            ('st_phylogroup_combinations', 'ST-Phylogroup', 'ST - Phylogroup'),
            ('st_fimh_combinations', 'ST-FimH', 'ST - FimH type'),
            ('st_fumc_combinations', 'ST-FumC', 'ST - FumC type'),
            ('st_fumc_fimh_combinations', 'ST-FumC:FimH', 'ST - CH type (FumC:FimH)')
        ]
        for key, title, desc in combos:
            combo_dict = patterns.get(key, {})
            if not combo_dict:
                continue
            html += f'<h3 style="margin-top:30px;">{title} Combinations</h3><input type="text" class="search-box" id="search-{key}" onkeyup="searchTable(\'{key}-table\',\'search-{key}\')" placeholder="🔍 Search...">'
            html += f'<div class="scrollable-table"><table id="{key}-table" class="data-table"><thead><tr><th data-sort="string">Combination</th><th data-sort="number">Count</th><th data-sort="string">Samples</th></tr></thead><tbody>'
            for combo, samples in sorted(combo_dict.items(), key=lambda x: len(x[1]), reverse=True):
                sample_list = ', '.join(samples)
                html += f'<tr><td><strong>{combo}</strong></td><td>{len(samples)}</td><td>{sample_list}</td></tr>'
            html += '</tbody></table></div>'
        full = patterns.get('st_oh_phylo_fumc_fimh_combinations', {})
        if full:
            html += f'<h3 style="margin-top:30px;">ST - O:H - Phylogroup - FumC:FimH Combinations</h3><input type="text" class="search-box" id="search-full" onkeyup="searchTable(\'full-combo-table\',\'search-full\')" placeholder="🔍 Search...">'
            html += f'<div class="scrollable-table"><table id="full-combo-table" class="data-table"><thead><tr><th data-sort="string">Full Combination</th><th data-sort="number">Count</th><th data-sort="string">Samples</th></tr></thead><tbody>'
            for combo, samples in sorted(full.items(), key=lambda x: len(x[1]), reverse=True):
                html += f'<tr><td><strong>{combo}</strong></td><td>{len(samples)}</td><td>{", ".join(samples)}</td></tr>'
            html += '</tbody></table></div>'
        return html
    
    def _serotype_section(self, kwargs):
        patterns = kwargs['patterns']
        samples = kwargs['samples_data']
        sero_dist = patterns.get('serotype_distribution', Counter())
        total = sum(sero_dist.values())
        html = f"""
        <div class="alert-box alert-info"><i class="fas fa-info-circle"></i><div><h3>Serotype Analysis (O:H)</h3><p>Serotyping identifies lipopolysaccharide (O) and flagellar (H) antigens. Specific serotypes are associated with clinical syndromes: O157:H7 (STEC), O6:H1 (UPEC), etc.</p><p><strong>{len(sero_dist)} unique serotypes</strong> identified.</p></div></div>
        <div class="scrollable-table"><table id="serotype-table" class="data-table"><thead><tr><th data-sort="string">Serotype</th><th data-sort="number">Count</th><th data-sort="number">Percentage</th><th data-sort="string">Common STs</th></tr></thead><tbody>
        """
        for sero, cnt in sero_dist.most_common():
            if sero == 'ND': continue
            pct = cnt/total*100
            sts = set()
            for combo in patterns.get('st_oh_combinations',{}):
                if f" - {sero}" in combo:
                    st_part = combo.split(" - ")[0]
                    sts.add(st_part)
            st_list = ', '.join(sts) if sts else 'Various'
            html += f'<tr><td><strong>{sero}</strong></td><td>{cnt}</td><td>{pct:.1f}%</td><td>{st_list}</td></tr>'
        html += '</tbody></table></div>'
        # O-type distribution with sample column
        o_dist = patterns.get('o_type_distribution', Counter())
        if o_dist:
            html += '<h3>O-type Distribution</h3><div class="scrollable-table"><table id="o-dist-table" class="data-table"><thead><tr><th data-sort="string">O-type</th><th data-sort="number">Count</th><th data-sort="string">Samples</th></tr></thead><tbody>'
            for o, cnt in o_dist.most_common():
                if o == 'ND': continue
                sample_list = ', '.join([s for s,d in samples.items() if d.get('serotype',{}).get('O_Type') == o])
                html += f'<tr><td><strong>{o}</strong></td><td>{cnt}</td><td>{sample_list}</td></tr>'
            html += '</tbody></table></div>'
        # H-type distribution with sample column
        h_dist = patterns.get('h_type_distribution', Counter())
        if h_dist:
            html += '<h3>H-type Distribution</h3><div class="scrollable-table"><table id="h-dist-table" class="data-table"><thead><tr><th data-sort="string">H-type</th><th data-sort="number">Count</th><th data-sort="string">Samples</th></tr></thead><tbody>'
            for h, cnt in h_dist.most_common():
                if h == 'ND': continue
                sample_list = ', '.join([s for s,d in samples.items() if d.get('serotype',{}).get('H_Type') == h])
                html += f'<tr><td><strong>{h}</strong></td><td>{cnt}</td><td>{sample_list}</td></tr>'
            html += '</tbody></table></div>'
        return html
    
    def _chtype_section(self, kwargs):
        patterns = kwargs['patterns']
        samples = kwargs['samples_data']
        ch_dist = patterns.get('ch_type_distribution', Counter())
        total = sum(ch_dist.values())
        html = f"""
        <div class="alert-box alert-info"><i class="fas fa-info-circle"></i><div><h3>CH Type (FumC:FimH) Analysis</h3><p>CH typing combines alleles of the housekeeping gene <em>fumC</em> and the type 1 fimbrial adhesin <em>fimH</em>. It provides high resolution for population studies and has been used to define epidemic clones.</p><p><strong>{len(ch_dist)} unique CH types</strong> identified.</p></div></div>
        <div class="scrollable-table"><table id="chtype-table" class="data-table"><thead><tr><th data-sort="string">CH Type (FumC:FimH)</th><th data-sort="number">Count</th><th data-sort="number">Percentage</th><th data-sort="string">Samples</th></tr></thead><tbody>
        """
        for cht, cnt in ch_dist.most_common():
            if cht == 'ND' or 'ND:' in cht: continue
            pct = cnt/total*100
            sample_list = ', '.join([s for s,d in samples.items() if d.get('chtyper',{}).get('CH_Type') == cht])
            html += f'<tr><td><strong>{cht}</strong></td><td>{cnt}</td><td>{pct:.1f}%</td><td>{sample_list}</td></tr>'
        html += '</tbody></table></div>'
        # FumC distribution with sample column
        fumc_dist = patterns.get('fumc_type_distribution', Counter())
        if fumc_dist:
            html += '<h3>FumC Allele Distribution</h3><div class="scrollable-table"><table id="fumc-dist-table" class="data-table"><thead><tr><th data-sort="string">FumC Type</th><th data-sort="number">Count</th><th data-sort="string">Samples</th></tr></thead><tbody>'
            for fumc, cnt in fumc_dist.most_common():
                if fumc == 'ND': continue
                sample_list = ', '.join([s for s,d in samples.items() if d.get('chtyper',{}).get('FumC_Type') == fumc])
                html += f'<tr><td><strong>{fumc}</strong></td><td>{cnt}</td><td>{sample_list}</td></tr>'
            html += '</tbody></table></div>'
        # FimH distribution with sample column
        fimh_dist = patterns.get('fimh_type_distribution', Counter())
        if fimh_dist:
            html += '<h3>FimH Allele Distribution</h3><div class="scrollable-table"><table id="fimh-dist-table" class="data-table"><thead><tr><th data-sort="string">FimH Type</th><th data-sort="number">Count</th><th data-sort="string">Samples</th></tr></thead><tbody>'
            for fimh, cnt in fimh_dist.most_common():
                if fimh == 'ND': continue
                sample_list = ', '.join([s for s,d in samples.items() if d.get('chtyper',{}).get('FimH_Type') == fimh])
                html += f'<tr><td><strong>{fimh}</strong></td><td>{cnt}</td><td>{sample_list}</td></tr>'
            html += '</tbody></table></div>'
        return html
    
    def _phylogroup_section(self, kwargs):
        patterns = kwargs['patterns']
        samples = kwargs['samples_data']
        phylo_dist = patterns.get('phylogroup_distribution', Counter())
        total = sum(phylo_dist.values())
        html = f"""
        <div class="alert-box alert-info"><i class="fas fa-info-circle"></i><div><h3>Phylogroup Analysis (Clermont scheme)</h3><p>E. coli is divided into phylogroups (A, B1, B2, C, D, E, F, G) that reflect ecological niches and pathogenic potential. B2 and D are associated with extra‑intestinal infections, while A and B1 are common in commensals and environmental strains.</p><p><strong>{len(phylo_dist)} unique phylogroups</strong> identified.</p></div></div>
        <div class="scrollable-table"><table id="phylogroup-table" class="data-table"><thead><tr><th data-sort="string">Phylogroup</th><th data-sort="number">Count</th><th data-sort="number">Percentage</th><th data-sort="string">Samples</th></tr></thead><tbody>
        """
        for ph, cnt in phylo_dist.most_common():
            if ph == 'ND': continue
            pct = cnt/total*100
            sample_list = ', '.join([s for s,d in samples.items() if d.get('phylogrouping',{}).get('Clermont_Type') == ph])
            html += f'<tr><td><strong>{ph}</strong></td><td>{cnt}</td><td>{pct:.1f}%</td><td>{sample_list}</td></tr>'
        html += '</tbody></table></div>'
        return html
    
    def _amr_section(self, kwargs):
        gene_centric = kwargs['gene_centric']
        amr_db = gene_centric.get('amr_databases', {})
        total_samples = len(kwargs['samples_data'])
        html = '<div class="alert-box alert-info"><i class="fas fa-info-circle"></i><div><h3>AMR Gene Analysis</h3><p>Each gene with all genomes. Filter by important resistance genes. Critical genes (ESBL, carbapenemases, mcr, etc.) are marked ⚠️.</p></div></div>'
        html += '<input type="text" class="search-box" id="search-amr" onkeyup="searchTable(\'amr-table\',\'search-amr\')" placeholder="🔍 Search AMR genes...">'
        html += '<div class="action-buttons">'
        # Individual filter buttons for major drug classes
        for label, pattern in [
            ("ESBL (CTX‑M)","blaCTX-M"), ("Carbapenemases (KPC)", "blaKPC"), ("Carbapenemases (NDM)", "blaNDM"), 
            ("Colistin (mcr)","mcr"), ("Quinolones (qnr)","qnr"), ("Aminoglycosides (aac)","aac"), ("Aminoglycosides (aph)","ant"), ("Trimethoprim (dfr)","dfr"), ("Quinolones (chromosomal mutations) (gyrA_)","gyrA_"),  ("Heavy metal resistance (sil)","sil"),
            ("Chloramphenicol (cat)","cat"), ("Fosfomycin (fos)","fos"), ("Sulfonamide (sul)","sul"), ("Chromosomal mutations (parC_)","parC_"), ("Chromosomal mutations) (parE_)","parE_"), (" Fosfomycin (uhpT_E350Q)","uhpT_E350Q"),  ("Heavy metal resistance (pco)","pco"),
            ("Tetracycline (tet)","tet"), ("Macrolides (erm)","erm"), ("Macrolides (mph)","mph"), ("Beta‑lactams (blaTEM)","blaTEM"), ("Beta‑lactams (blaEC)","blaEC"), ("Carbapenemases (OXA)","OXA"), ("Heavy metal resistance (mer)","mer"), ("Plasmid Replicons (plasmid)","plasmidfinder")
        ]:
            html += f'<button class="action-btn btn-warning" onclick="document.getElementById(\'search-amr\').value=\'{pattern}\'; searchTable(\'amr-table\',\'search-amr\')">{label}</button>'
        html += '<button class="action-btn btn-light" onclick="document.getElementById(\'search-amr\').value=\'\'; searchTable(\'amr-table\',\'search-amr\')"><i class="fas fa-sync"></i> Clear</button>'
        html += '</div><div class="scrollable-table"><table id="amr-table" class="data-table"><thead><tr><th data-sort="string">Gene</th><th data-sort="string">Database</th><th data-sort="number">Count</th><th data-sort="number">%</th><th data-sort="string">Genomes</th></tr></thead><tbody>'
        all_genes = []
        for db, genes in amr_db.items():
            all_genes.extend(genes)
        all_genes.sort(key=lambda x: x['count'], reverse=True)
        for g in all_genes:
            pct = f"{(g['count']/total_samples)*100:.1f}%" if total_samples else "0%"
            is_critical = any(crit.lower() in g['gene'].lower() for crit in self.data_analyzer.critical_amr_genes)
            gene_display = f"<strong>{g['gene']}</strong>" + (" ⚠️" if is_critical else "")
            genome_tags = ''.join(f'<span class="genome-tag">{gen}</span>' for gen in g['genomes'])
            html += f'<tr><td>{gene_display}</td><td>{g["database"]}</td><td>{g["count"]}</td><td>{pct}</td><td><div class="genome-list">{genome_tags}</div></td></tr>'
        html += '</tbody></table></div>'
        return html
    
    def _virulence_section(self, kwargs):
        gene_centric = kwargs['gene_centric']
        vir_db = gene_centric.get('virulence_databases', {})
        total_samples = len(kwargs['samples_data'])
        html = '''
        <div class="alert-box alert-info">
            <i class="fas fa-info-circle fa-2x"></i>
            <div>
                <h3>Virulence Gene Analysis</h3>
                <p>Each gene with all genomes. Filter by key pathotypes. Critical virulence genes (Shiga toxins, intimin, CNF1, etc.) are marked ⚠️.</p>
            </div>
        </div>
        <input type="text" class="search-box" id="search-vir" onkeyup="searchTable('vir-table','search-vir')" placeholder="🔍 Search virulence genes...">
        <div class="action-buttons">
        '''
        # Full list of filters – exactly as you had (plus a few more)
        filters = [
            ("Shiga toxins (stx)", "stx"), ("Intimin (eae)", "eae"), ("CNF1", "cnf1"),
            ("Hemolysin (hly)", "hly"), ("LT toxin", "lt"), ("ST toxin", "st"),
            ("EAST-1 toxin", "east1"), ("Cytolethal distending toxin", "cdt"),
            ("Colibactin", "clb"), ("Lpf fimbriae", "lpf"), ("Stg fimbriae", "stg"),
            ("Efa1/LifA", "efa1"), ("FdeC", "fdec"), ("Agn43", "agn43"), ("EaeH", "eaeh"),
            ("Type 1 fimbriae (fim)", "fim"), ("Curli (csg)", "csg"), ("ECP pilus (ecp)", "ecp"),
            ("Aerobactin (iuc)", "iuc"), ("Yersiniabactin (ybt)", "ybt"), ("Salmochelin (iro)", "iro"),
            ("Enterobactin (ent)", "ent"), ("Flagella (fl)", "fl"), ("T3SS effectors (esp)", "esp"),
            ("T6SS (tss)", "tss"), ("Kps capsule", "kps"), ("Iss serum resistance", "iss"),
            ("TraT", "trat"), ("Cah", "cah"), ("Ompt protease", "ompt"), ("Invasion (ibe)", "ibe"),
            ("Ycb fimbrial cluster", "ycb"), ("OmpA", "omp"), ("Chu heme uptake", "chu"),
            ("Sit transport", "sit"), ("Fep transport", "fep"), ("TccP", "tccp"), ("Map", "map"),
            ("Cif", "cif"), ("Paa", "paa"), ("T3SS structural (esc)", "esc"), ("T3SS structural (sep)", "sep"),
            ("T3SS structural (ces)", "ces"), ("T3SS structural (ler)", "ler"), ("T6SS (hcp)", "hcp"),
            ("T6SS (vgrG)", "vgrG"), ("Neu capsule", "neu")
        ]
        color_classes = ['btn-primary', 'btn-success', 'btn-warning', 'btn-danger', 'btn-info', 'btn-secondary']
        for idx, (label, pattern) in enumerate(filters):
            color = color_classes[idx % len(color_classes)]
            html += f'<button class="action-btn {color}" onclick="document.getElementById(\'search-vir\').value=\'{pattern}\'; searchTable(\'vir-table\',\'search-vir\')">{label}</button>'
        html += '<button class="action-btn btn-light" onclick="document.getElementById(\'search-vir\').value=\'\'; searchTable(\'vir-table\',\'search-vir\')">Clear</button>'
        html += '</div>'   

        # Table (unchanged)
        html += '<div class="scrollable-table"><table id="vir-table" class="data-table"><thead><tr><th data-sort="string">Gene</th><th data-sort="string">Database</th><th data-sort="number">Count</th><th data-sort="number">%</th><th data-sort="string">Genomes</th></tr></thead><tbody>'
        all_genes = []
        for db, genes in vir_db.items():
            all_genes.extend(genes)
        all_genes.sort(key=lambda x: x['count'], reverse=True)
        for g in all_genes:
            pct = f"{(g['count']/total_samples)*100:.1f}%" if total_samples else "0%"
            is_critical = any(crit.lower() in g['gene'].lower() for crit in self.data_analyzer.critical_virulence_genes)
            gene_display = f"<strong>{g['gene']}</strong>" + (" ⚠️" if is_critical else "")
            genome_tags = ''.join(f'<span class="genome-tag">{gen}</span>' for gen in g['genomes'])
            html += f'<tr><td>{gene_display}</td><td>{g["database"]}</td><td>{g["count"]}</td><td>{pct}</td><td><div class="genome-list">{genome_tags}</div></td></tr>'
        html += '</tbody></table></div>'
        return html
    
    def _patterns_section(self, kwargs):
        patterns = kwargs['patterns']
        html = '<div class="alert-box alert-info"><i class="fas fa-info-circle"></i><div><h3>Cross-Genome Patterns</h3><p>High-risk combinations and gene co-occurrence.</p></div></div>'
        high = patterns.get('high_risk_combinations', [])
        if high:
            html += f'<div class="alert-box alert-danger"><i class="fas fa-radiation fa-2x"></i><div><h3>⚠️ {len(high)} High-Risk Samples</h3><p>Carry both critical AMR and virulence genes.</p></div></div>'
            html += '<input type="text" class="search-box" id="search-highrisk" onkeyup="searchTable(\'highrisk-table\',\'search-highrisk\')" placeholder="🔍 Search high‑risk combinations...">'
            html += '<div class="scrollable-table"><table id="highrisk-table" class="data-table"><thead><tr><th data-sort="string">Sample</th><th data-sort="string">ST</th><th data-sort="string">Serotype</th><th data-sort="string">Critical AMR</th><th data-sort="string">Critical Virulence</th></tr></thead><tbody>'
            for h in high:
                html += f'<tr><td><strong>{h["sample"]}</strong></td><td>{h["st"]}</td><td>{h["serotype"]}</td><td>{", ".join(h["critical_amr_genes"])}</td><td>{", ".join(h["critical_virulence_genes"])}</td></tr>'
            html += '</tbody></table></div>'
        cooc = patterns.get('gene_cooccurrence', {})
        cooc_list = []
        for g1, partners in cooc.items():
            for g2, cnt in partners.items():
                cooc_list.append((g1, g2, cnt))
        cooc_list.sort(key=lambda x: x[2], reverse=True)
        if cooc_list:
            html += '<h3>Top 100 Gene Co-occurrences</h3><input type="text" class="search-box" id="search-cooc" onkeyup="searchTable(\'cooc-table\',\'search-cooc\')" placeholder="🔍 Search co‑occurrence pairs...">'
            html += '<div class="scrollable-table"><table id="cooc-table" class="data-table"><thead><tr><th data-sort="string">Gene 1</th><th data-sort="string">Gene 2</th><th data-sort="number">Co-occurrence Count</th></tr></thead><tbody>'
            for g1, g2, cnt in cooc_list[:100]:
                html += f'<tr><td>{g1}</td><td>{g2}</td><td>{cnt}</td></tr>'
            html += '</tbody></table></div>'
        return html
    
    def _qc_section(self, kwargs):
        qc_data = kwargs.get('qc_data', {})
        if not qc_data:
            return '<div class="alert-box alert-warning"><i class="fas fa-exclamation-circle"></i><div>No FASTA QC data found. Please ensure FASTA_QC_summary.html is present.</div></div>'
        metrics = set()
        for d in qc_data.values():
            metrics.update(d.keys())
        metrics = sorted(metrics)
        html = '<div class="alert-box alert-info"><i class="fas fa-chart-line"></i><div>FASTA Quality Control metrics for each genome.</div></div>'
        html += '<input type="text" class="search-box" id="search-qc" onkeyup="searchTable(\'qc-table\',\'search-qc\')" placeholder="🔍 Search sample...">'
        html += '<div class="scrollable-table"><table id="qc-table" class="data-table"><thead><tr><th data-sort="string">Sample</th>'
        for m in metrics:
            html += f'<th data-sort="number">{m}</th>'
        html += '</tr></thead><tbody>'
        for sample, vals in sorted(qc_data.items()):
            html += f'<tr><td><strong>{sample}</strong></td>'
            for m in metrics:
                v = vals.get(m, 'ND')
                if isinstance(v, float):
                    v = f"{v:,.0f}" if v > 1000 else f"{v:.2f}"
                html += f'<td>{v}</td>'
            html += '</tr>'
        html += '</tbody></table></div>'
        return html
    
    def _aiguide_section(self, kwargs):
        return """
        <div class="alert-box alert-info"><i class="fas fa-robot fa-2x"></i><div><h3>AI Assistant Guide</h3><p>Upload this HTML or the JSON file to ChatGPT, Claude, or Gemini to ask questions.</p></div></div>
        <div class="database-section"><h4>Example questions for E. coli:</h4><ul>
        <li>Which STs carry mcr-1 or other colistin resistance genes?</li>
        <li>List all samples with Shiga toxin genes (stx1/stx2) and intimin (eae).</li>
        <li>What is the most common phylogroup among ST131?</li>
        <li>Show me ST-O:H combinations associated with high-risk virulence profiles.</li>
        <li>Which resistance genes co-occur most frequently with blaCTX-M?</li>
        </ul></div>
        """
    
    def _export_section(self, kwargs):
        return """
        <div class="alert-box alert-info"><i class="fas fa-download"></i><div>Export data tables as CSV or download complete JSON.</div></div>
        <div class="action-buttons">
            <button class="action-btn btn-primary" onclick="exportTableToCSV('samples-table','sample_overview.csv')">Sample Overview CSV</button>
            <button class="action-btn btn-primary" onclick="exportTableToCSV('amr-table','amr_genes.csv')">AMR Genes CSV</button>
            <button class="action-btn btn-primary" onclick="exportTableToCSV('vir-table','virulence_genes.csv')">Virulence Genes CSV</button>
            <button class="action-btn btn-primary" onclick="exportTableToCSV('highrisk-table','high_risk.csv')">High-Risk CSV</button>
            <button class="action-btn btn-primary" onclick="exportTableToCSV('qc-table','fasta_qc.csv')">FASTA QC CSV</button>
            <button class="action-btn btn-success" onclick="location.href='genius_ultimate_report.json'">Download JSON</button>
        </div>
        """


# =============================================================================
# MASTER REPORTER CLASS
# =============================================================================
class GeniusUltimateReporter:
    """
    Orchestrates the entire analysis pipeline:
    1. Find all HTML report files in the input directory.
    2. Parse each report and integrate data.
    3. Generate JSON, CSV, and HTML outputs.
    """
    
    def __init__(self, input_dir: Path):
        self.input_dir = Path(input_dir)
        self.output_dir = self.input_dir / "GENIUS_ULTIMATE_REPORTS"
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.parser = UltimateHTMLParser()
        self.analyzer = UltimateDataAnalyzer()
        self.html_generator = UltimateHTMLGenerator(self.analyzer)
        self.metadata = {
            "tool_name": "GENIUS E.coli Ultimate Reporter",
            "version": "2.0.0",
            "author": "Brown Beckley <brownbeckley94@gmail.com>",
            "affiliation": "University of Ghana Medical School",
            "analysis_date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "input_directory": str(self.input_dir)
        }
    
    def find_html_files(self) -> Dict[str, List[Path]]:
        """
        Recursively search for HTML report files and classify by type.
        Returns a dictionary with keys: mlst, serotype, chtyper, phylogrouping, amrfinder, abricate, qc.
        """
        print("🔍 Searching for HTML reports...")
        html_files = {
            'mlst': [], 'serotype': [], 'chtyper': [], 'phylogrouping': [],
            'amrfinder': [], 'abricate': [], 'qc': []
        }
        for html_file in self.input_dir.glob("**/*.html"):
            name = html_file.name.lower()
            if 'mlst' in name:
                html_files['mlst'].append(html_file)
            elif 'serotype' in name:
                html_files['serotype'].append(html_file)
            elif 'chtyper' in name or 'fumc' in name:
                html_files['chtyper'].append(html_file)
            elif 'phylogroup' in name or 'clermont' in name:
                html_files['phylogrouping'].append(html_file)
            elif 'amr' in name or 'resistance' in name:
                html_files['amrfinder'].append(html_file)
            elif 'fasta_qc' in name or 'qc_summary' in name:
                html_files['qc'].append(html_file)
            elif 'abricate' in name or any(db in name for db in self.parser.abricate_databases):
                html_files['abricate'].append(html_file)
        # Report found files
        for k, v in html_files.items():
            if v:
                print(f"  📁 {k.upper()}: {len(v)} files found")
        return html_files
    
    def integrate_all_data(self, html_files: Dict[str, List[Path]]) -> Dict[str, Any]:
        """
        Parse all HTML reports and merge data into a single integrated dictionary.
        """
        print("\n🔗 Integrating data...")
        integrated = {
            'metadata': self.metadata,
            'samples': {},
            'patterns': {},
            'gene_centric': {},
            'qc_data': {}
        }
        
        # Parse QC report if available
        if html_files['qc']:
            integrated['qc_data'] = self.parser.parse_qc_report(html_files['qc'][0])
        
        # Parse MLST
        mlst_data = {}
        if html_files['mlst']:
            mlst_data = self.parser.parse_mlst_report(html_files['mlst'][0])
        
        # Parse Serotype
        serotype_data = {}
        if html_files['serotype']:
            serotype_data = self.parser.parse_serotype_report(html_files['serotype'][0])
        
        # Parse CHTyper
        chtyper_data = {}
        if html_files['chtyper']:
            chtyper_data = self.parser.parse_chtyper_report(html_files['chtyper'][0])
        
        # Parse Phylogrouping
        phylogrouping_data = {}
        if html_files['phylogrouping']:
            phylogrouping_data = self.parser.parse_phylogrouping_report(html_files['phylogrouping'][0])
        
        # Parse AMRfinder
        amr_by_sample, amr_gene_freq = {}, {}
        if html_files['amrfinder']:
            amr_by_sample, amr_gene_freq = self.parser.parse_amrfinder_report(html_files['amrfinder'][0])
        
        # Parse ABRicate databases
        abricate_by_sample = defaultdict(dict)
        abricate_gene_freq = {}
        for f in html_files['abricate']:
            genes_by_sample, gene_freq = self.parser.parse_abricate_database_report(f)
            # Determine database name (simplified)
            db_name = 'unknown'
            for db in self.parser.abricate_databases:
                if db in f.name.lower():
                    db_name = db
                    break
            for samp, gs in genes_by_sample.items():
                abricate_by_sample[samp][db_name] = gs
            abricate_gene_freq[db_name] = gene_freq
        
        # Collect all unique sample IDs
        all_samples = set()
        all_samples.update(mlst_data.keys())
        all_samples.update(serotype_data.keys())
        all_samples.update(chtyper_data.keys())
        all_samples.update(phylogrouping_data.keys())
        all_samples.update(amr_by_sample.keys())
        all_samples.update(abricate_by_sample.keys())
        all_samples.update(integrated['qc_data'].keys())
        
        if not all_samples:
            print("❌ No samples found in any report!")
            return {}
        
        print(f"📊 Found {len(all_samples)} unique samples")
        
        # Integrate data for each sample
        for sample in all_samples:
            # Collect virulence genes from VFDB and ecoli_vf databases
            virulence_genes = []
            for db in ['vfdb', 'ecoli_vf']:
                if db in abricate_by_sample.get(sample, {}):
                    virulence_genes.extend(abricate_by_sample[sample][db])
            
            integrated['samples'][sample] = {
                'mlst': mlst_data.get(sample, {'ST': 'ND', 'Allele_Profile': 'ND'}),
                'serotype': serotype_data.get(sample, {'Serotype': 'ND', 'O_Type': 'ND', 'H_Type': 'ND'}),
                'chtyper': chtyper_data.get(sample, {'FumC_Type': 'ND', 'FimH_Type': 'ND', 'CH_Type': 'ND'}),
                'phylogrouping': phylogrouping_data.get(sample, {'Clermont_Type': 'ND'}),
                'amr_genes': amr_by_sample.get(sample, []),
                'virulence_genes': list(set(virulence_genes))  # remove duplicates
            }
        
        # Store gene frequencies for gene-centric tables
        integrated['gene_frequencies'] = {
            'amrfinder': amr_gene_freq,
            'abricate': abricate_gene_freq
        }
        
        # Generate gene-centric tables and cross-genome patterns
        print("\n🧠 Processing gene-centric analysis...")
        integrated['gene_centric'] = self.analyzer.create_gene_centric_tables(integrated)
        integrated['patterns'] = self.analyzer.create_cross_genome_patterns(integrated)
        
        return integrated
    
    def generate_json_report(self, data: Dict[str, Any]) -> Path:
        """Save all integrated data as a JSON file."""
        print("\n📝 Generating JSON report...")
        out = self.output_dir / "genius_ultimate_report.json"
        # Use default=str to handle non-serializable objects (e.g., Path)
        with open(out, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, default=str)
        print(f"    ✅ JSON saved: {out}")
        return out
    
    def generate_csv_reports(self, data: Dict[str, Any]):
        """Generate CSV files for sample overview, AMR genes, virulence genes, and high-risk combinations."""
        print("\n📊 Generating CSV reports...")
        
        # Sample overview CSV
        samples_df = pd.DataFrame([{
            'Sample': s,
            'ST': d['mlst']['ST'],
            'Serotype': d['serotype']['Serotype'],
            'Phylogroup': d['phylogrouping']['Clermont_Type'],
            'CH_Type': d['chtyper']['CH_Type'],
            'AMR_Count': len(d['amr_genes']),
            'Virulence_Count': len(d['virulence_genes'])
        } for s, d in data['samples'].items()])
        samples_df.to_csv(self.output_dir / "sample_overview.csv", index=False)
        
        # AMR genes CSV (gene-centric)
        amr_rows = []
        for db, genes in data['gene_centric'].get('amr_databases', {}).items():
            for g in genes:
                amr_rows.append({
                    'Gene': g['gene'],
                    'Database': g['database'],
                    'Count': g['count'],
                    'Genomes': ';'.join(g['genomes'])
                })
        if amr_rows:
            pd.DataFrame(amr_rows).to_csv(self.output_dir / "amr_genes.csv", index=False)
        
        # Virulence genes CSV
        vir_rows = []
        for db, genes in data['gene_centric'].get('virulence_databases', {}).items():
            for g in genes:
                vir_rows.append({
                    'Gene': g['gene'],
                    'Database': g['database'],
                    'Count': g['count'],
                    'Genomes': ';'.join(g['genomes'])
                })
        if vir_rows:
            pd.DataFrame(vir_rows).to_csv(self.output_dir / "virulence_genes.csv", index=False)
        
        # High-risk combinations CSV
        high = data['patterns'].get('high_risk_combinations', [])
        if high:
            pd.DataFrame(high).to_csv(self.output_dir / "high_risk_combinations.csv", index=False)
        
        print("    ✅ CSV reports generated.")
    
    def run(self):
        """Execute the complete analysis pipeline."""
        print("=" * 80)
        print("🧠 GENIUS E.COLI ULTIMATE REPORTER v2.0.0")
        print("=" * 80)
        print(f"📁 Input directory: {self.input_dir}")
        
        # Find all HTML files
        html_files = self.find_html_files()
        if not any(html_files.values()):
            print("❌ No HTML report files found!")
            return False
        
        # Integrate data from all reports
        data = self.integrate_all_data(html_files)
        if not data:
            return False
        
        # Generate output files
        print("\n" + "=" * 80)
        print("📊 GENERATING ULTIMATE REPORTS")
        print("=" * 80)
        self.generate_json_report(data)
        self.generate_csv_reports(data)
        self.html_generator.generate_main_report(data, self.output_dir)
        
        # Print summary
        total_samples = len(data['samples'])
        patterns = data['patterns']
        high_risk = len(patterns.get('high_risk_combinations', []))
        gene_centric = data['gene_centric']
        total_amr = sum(len(genes) for genes in gene_centric.get('amr_databases', {}).values())
        total_vir = sum(len(genes) for genes in gene_centric.get('virulence_databases', {}).values())
        
        print("\n" + "=" * 80)
        print("✅ ULTIMATE ANALYSIS COMPLETE!")
        print("=" * 80)
        print(f"📁 Output directory: {self.output_dir}")
        print(f"📄 Files generated:")
        print(f"   • genius_ultimate_report.html (Interactive report)")
        print(f"   • genius_ultimate_report.json (Complete data)")
        print(f"   • sample_overview.csv (Sample data)")
        print(f"   • amr_genes.csv (Gene-centric AMR data)")
        print(f"   • virulence_genes.csv (Gene-centric virulence data)")
        print(f"   • high_risk_combinations.csv (Pattern analysis)")
        if data.get('qc_data'):
            print(f"   • fasta_qc.csv (FASTA QC metrics) – export from QC tab")
        
        print(f"\n📈 ANALYSIS SUMMARY:")
        print(f"   • {total_samples} total samples analyzed")
        print(f"   • {total_amr} AMR genes across all databases")
        print(f"   • {total_vir} virulence genes")
        print(f"   • {high_risk} high-risk AMR+virulence combinations")
        
        print("\n🎯 Next steps:")
        print("   1. Open genius_ultimate_report.html in your browser")
        print("   2. Explore AMR and Virulence tabs to see genes with ALL their genomes")
        print("   3. Use filter buttons to focus on key resistance/virulence genes")
        print("   4. Examine combination tables under MLST, Serotype, CH Type, and Phylogroup tabs")
        print("   5. Use print buttons on each section header to print specific sections")
        print("   6. Export data using the Export tab or individual CSV buttons")
        
        print("\n" + "=" * 80)
        return True


# =============================================================================
# MAIN ENTRY POINT
# =============================================================================
def main():
    parser = argparse.ArgumentParser(
        description='GENIUS E.coli Ultimate Reporter - Gene-Centric Analysis',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python genius_ecoli_ultimate_reporter.py -i /path/to/html/reports

Author: Brown Beckley <brownbeckley94@gmail.com>
Affiliation: University of Ghana Medical School, Department of Medical Biochemistry
        """
    )
    parser.add_argument('-i', '--input-dir', required=True,
                        help='Directory containing HTML report files')
    parser.add_argument('-o', '--output-dir',
                        help='Custom output directory (default: input_dir/GENIUS_ULTIMATE_REPORTS)')
    
    args = parser.parse_args()
    input_dir = Path(args.input_dir)
    
    if not input_dir.exists():
        print(f"❌ Input directory not found: {input_dir}")
        sys.exit(1)
    
    reporter = GeniusUltimateReporter(input_dir)
    
    if args.output_dir:
        reporter.output_dir = Path(args.output_dir)
        reporter.output_dir.mkdir(parents=True, exist_ok=True)
    
    success = reporter.run()
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()